#!/bin/bash

current_folder=${1:-"."}
N_numberoflines=${2:-"0"}

echo "--> FASTASCAN Results <--"

echo "There are a total of $(find $current_folder -type f -name "*.fasta" -or -name "*.fa" | wc -l) .fasta and .fa files in the scanned folder."

echo "The amount of unique Fasta IDs in the .fasta and .fa files is:"
awk '$1~/>/{print $1}' $(find $current_folder -type f -name "*.fasta" -or -name "*.fa") | sort | uniq | wc -l


echo " "
echo "Let's see the files individually:"
for i in $(find "$current_folder" -type f -name "*.fasta" -or -name "*.fa")
do echo "---- For file "$i" :"
if [[ -f "$i" ]]; then echo " > Is a file, not a symlink."; else echo " > Is a symlink."; fi;
echo " > It contains $(grep ">" -c $i) sequences, and those have a total length of $(awk '$1!~/>/{print $0}' "$i" | tr '\n' ' ' | sed 's/ //g' | sed 's/-//g'| wc -m)."
echo ">>> Total content:"
do if [[ $N_numberoflines -eq 0 ]]; then break
elif [[ $(wc -l < "$i") -le $((2*$N_numberoflines)) ]]; then cat "$i"
else head -n $N_numberoflines
echo "..."
tail -n $N_numberoflines
fi
done

#for the total sequence length, look at the END and counter
# wc -m sums characters (combinable with awk read y condición de NO tiene > y replace "-", " ", ";", "\n" with nada to delete them
#--> TESTEA  si las new lines se cuentan con wc -m

 
 #CURRENT VERSION: NOV 16
